### ISSUE TITLE
笔试题1反馈

### ISSUE THREAD

**Issue by zhugw** [clinch-123/MyInterview#1]
用新的样例数据验收的时候报错 

```
org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 2
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:81) ~[mybatis-3.5.13.jar:3.5.13]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425) ~[mybatis-spring-3.0.2.jar:3.0.2]
	at jdk.proxy2/jdk.proxy2.$Proxy60.selectOne(Unknown Source) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:160) ~[mybatis-spring-3.0.2.jar:3.0.2]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87) ~[mybatis-3.5.13.jar:3.5.13]
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:142) ~[mybatis-3.5.13.jar:3.5.13]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86) ~[mybatis-3.5.13.jar:3.5.13]
	at jdk.proxy2/jdk.proxy2.$Proxy61.dictMate(Unknown Source) ~[na:na]
```
另外报文格式有2种情况
<img width="818" alt="image" src="https://github.com/clinch-123/MyInterview/assets/4953871/3a9fa5a4-194b-4ef0-b93d-1a677be96768">

验收样例数据见
[sample500.csv.zip](https://github.com/clinch-123/MyInterview/files/13258937/sample500.csv.zip)

**Comment by zhugw** [comment]
以及 仅仅这个SQL
```
SELECT value
        FROM dict
        WHERE
        (#{value} LIKE CONCAT('%', key1, '%') and #{value} LIKE CONCAT('%', key2, '%') and #{value} LIKE CONCAT('%', key3, '%'))
        or
        (#{value} LIKE CONCAT('%', key1, '%') and #{value} LIKE CONCAT('%', key2, '%'))
```
是否能实现该需求？
> 按照关键词多的排在前面 如先匹配3个关键词都有的 再匹配2个关键词都有的 最后匹配只有1个的
